services:
  - type: web
    name: aspnet-api
    env: docker
    plan: free
    region: frankfurt  # You can set a region, e.g., 'oregon' or 'frankfurt'
    dockerfilePath: D:\4 course\CourseWork\FitTrack\FitTrack.API\FitTrack.API\Dockerfile  # Path to your Dockerfile for the API
    buildCommand: dotnet publish -c Release -o out  # Builds the .NET project
    startCommand: dotnet out/YourAppName.dll  # Start command to run the API
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL  # Provided automatically when using Render PostgreSQL
        fromDatabase: aspnet-postgres
      - key: CONNECTIONSTRINGS__DEFAULTCONNECTION  # For appsettings.json
        fromDatabase: aspnet-postgres
    healthCheckPath: /
    #region: frankfurt

  - type: postgres
    name: aspnet-postgres
    plan: free
    version: 16
    # Optionally, set environment variables for PostgreSQL credentials
    # You can also let Render automatically set the DATABASE_URL
    envVars:
      - key: POSTGRES_DB
        value: FitTrack
      - key: POSTGRES_USER
        value: admin_db
      - key: POSTGRES_PASSWORD
        value: password
