// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDTF0tuHI-W7ZINk4VT9eWFLPq-rSPRwQ',
    appId: '1:517167028721:android:f638fdf36d72ce1a35cc50',
    messagingSenderId: '517167028721',
    projectId: 'fittrack-a4174',
    storageBucket: 'fittrack-a4174.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHR1o0H9O28Msx8q31mA3VfuOGxQjJa9o',
    appId: '1:517167028721:ios:658dae44d2062f6235cc50',
    messagingSenderId: '517167028721',
    projectId: 'fittrack-a4174',
    storageBucket: 'fittrack-a4174.firebasestorage.app',
    androidClientId: '517167028721-gv2mh6v4mvl6p3rue3hnqh05q5aglek8.apps.googleusercontent.com',
    iosClientId: '517167028721-4aa50lshd2ugld0phig9if04uo0mnmsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.fittrackMobileApp',
  );

}