name: Build and Push Docker Image

on:
  push:
    branches:
      - API  
  pull_request:
    branches:
      - API 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: gravelino  
          password: hehvoq-kUwpig-4zifbi 

      - name: Build Docker image
        run: |
          docker build -t gravelino/fittrackapirepo:${{ github.sha }} .
      
      - name: Tag Docker image
        run: |
          docker tag gravelino/fittrackapirepo:${{ github.sha }} gravelino/fittrackapirepo:latest

      - name: Push Docker image
        run: |
          docker push gravelino/fittrackapirepo:${{ github.sha }}
          docker push gravelino/fittrackapirepo:latest
